export const BOOK_VEHICLE = 'BOOK_VEHICLE';
export const SAVE_VEHICLE_DETAILS = 'SAVE_VEHICLE_DETAILS';
export const CLEAR_VEHICLE_DETAILS = 'CLEAR_VEHICLE_DETAILS';

export const BOOK_VEHICLE_INCREASE_QTY = 'BOOK_VEHICLE_INCREASE_QTY';
export const BOOK_VEHICLE_DECREASE_QTY = 'BOOK_VEHICLE_DECREASE_QTY';

export const CLEAR_BOOKED_VEHICLE = 'CLEAR_BOOKED_VEHICLE';

export const MAKE_VEHICLE_RESERVATION = 'MAKE_VEHICLE_RESERVATION';
export const CLEAR_VEHICLE_RESERVATION = 'CLEAR_VEHICLE_RESERVATION';
export const RESERVATION_QTY_INCREASE = 'RESERVATION_QTY_INCREASE';
export const RESERVATION_QTY_DECREASE = 'RESERVATION_QTY_DECREASE';

export const MAKE_VEHICLE_PAYMENT = 'MAKE_VEHICLE_PAYMENT';
